- name: " ansible playbook for the sql  "
  hosts: [mysql]
  become: yes
  vars:
    password: " ExpenseApp@1 "
    host: " mysql.daws19.online "
    user: " root "
  tasks:
    - name: "download mysql server"
      ansible.builtin.command: " dnf install mysql-server -y "

    - name: "starting and enabling the service"
      ansible.builtin.command: " systemctl start mysqldmysql.daws19.online "

    - name: "enabling the mysql server"
      ansible.builtin.command: " systemctl enable mysqld "
    
    - name: "login into mysql server "
      community.mysql.mysql_info:
        login_user: "{{ user }}"
        login_password: "{{ password }}"
        login_host: "{{ host }}"
      ignore_errors: true
      register: mysql
    
    - name: printing the mysql information
      ansible.builtin.debug:
        msg : "{{ mysql }}"

    - name: "setting the password and the user"
      ansible.builtin.command: " mysql_secure_installation --set-{{root}}-pass {{ password }}"
      